### ISSUE TITLE
Middleware scopes

### ISSUE THREAD

**Issue by MartkCz** [spiral/framework#1158] opened 2024-10-15 10:58 UTC
### Description

I'm following the instructions from the docs (https://spiral.dev/docs/http-middleware/current/en#combine-with-ioc-scopes and https://spiral.dev/docs/http-middleware/current/en#non-direct-scope-configuration), but none of them work. I even tried with a clean project and copied the exact code.

**Non-Direct Scope Configuration**

Can't resolve `App\UserContext`: undefined class or binding `Psr\Http\Message\ServerRequestInterface`.

```php
class UserContextBootloader extends Bootloader
{
    protected const BINDINGS = [
        UserContext::class => [self::class, 'userContext']
    ];

    private function userContext(ServerRequestInterface $request/* <--- problem */): UserContext
    {
        $userContext = $request->getAttribute('userContext', null);
        if ($userContext === null) {
            throw new ScopeException('Unable to resolve UserContext, invalid request scope');
        }

        return $userContext;
    }
}
```

**Combine with IoC scopes**

Recursive proxy detected for `Spiral\Session\SessionFactoryInterface` in `root` scope.

When I remove the `SessionBootloader` and `SessionMiddleware`, everything works fine until I try to access a property from `Spiral\Auth\AuthContextInterface`.

Recursive proxy detected for `Spiral\Auth\AuthContextInterface` in `root.http-request` scope.

```php
class MyMiddleware implements MiddlewareInterface
{

    public function __construct(
        private ScopeInterface $scope,
    )
    {
    }

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        return $this->scope->runScope([ // <--- problem runScope()
            UserContext::class => new UserContext(123, 'test')
        ], function () use ($handler, $request) {
            return $handler->handle($request);
        });
    }

}
```

When I look at the code, I see that the approach is different. Is the documentation outdated, or is this a bug?

```php
public function defineBindings(): array
{
    $this->binder
        ->getBinder(Spiral::Http)
        ->bind(
            AuthContextInterface::class,
            static fn (?ServerRequestInterface $request): AuthContextInterface =>
                ($request ?? throw new InvalidRequestScopeException(AuthContextInterface::class))
                    ->getAttribute(AuthMiddleware::ATTRIBUTE) ?? throw new ContextualObjectNotFoundException(
                        AuthContextInterface::class,
                        AuthMiddleware::ATTRIBUTE,
                    )
        );
    $this->binder->bind(AuthContextInterface::class, new Proxy(AuthContextInterface::class, false));

    return [];
}
```

### Additional Info

| Q                   | A
| ------------------- | ---
| Framework Version   | 3.14.5 
| PHP version         | 8.3.10 
| Operating system    | Linux

**Comment by roxblnfk** [comment] 2024-10-27 19:49
I made a few fixes in https://github.com/spiral/framework/releases/tag/3.14.6 about it.
It would be great to check that issue was fixed.

**Comment by MartkCz** [comment] 2024-11-05 19:33
Sorry for the delay. I tested the new version.

The issue with the `SessionBootloader` has been resolved, but when I try to run the following code

```php
    public function __construct(
        private AuthContextInterface $context,
        private UserContext $userContext,
    )
    {
    }

    #[Route(route: '/', name: 'index')]
    public function index(): string
    {
        var_dump($this->context->getToken());
        var_dump($this->userContext->id);
```

An exception is thrown: Recursive proxy detected for `Spiral\Auth\AuthContextInterface`.

I attempted to change `Spiral::Http` to `Spiral::HttpRequest` and everything worked fine after that.

https://github.com/spiral/framework/blob/master/src/Framework/Bootloader/Auth/HttpAuthBootloader.php#L59

---

Unfortunately, the first example with UserContextBootloader does not work.

![image](https://github.com/user-attachments/assets/fc0a639f-a998-417b-bc8f-93cbef19e23a)

**Comment by vokomarov** [comment] 2024-11-15 17:38
I am having the same error:

Recursive proxy detected for `Spiral\\Auth\\AuthContextInterface`.
Binding scope: `root`.
Calling scope: `root.http-request`.

on versions `>=3.14.0` while I'm running tests with fake HTTP calls: https://github.com/cash-track/api/blob/master/tests/Traits/InteractsWithHttp.php#L28

**Comment by roxblnfk** [comment] 2024-11-25 18:09
Hi @MartkCz
I inserted `UserContextBootloader` from your example into my test project.

```php
class UserContextBootloader extends Bootloader
{
    protected const BINDINGS = [
        UserContext::class => [self::class, 'userContext']
    ];

    private function userContext(ServerRequestInterface $request/* <--- problem */): UserContext
    {
        $userContext = $request->getAttribute('userContext', null);
        if ($userContext === null) {
            throw new ScopeException('Unable to resolve UserContext, invalid request scope');
        }

        return $userContext;
    }
}
```

Added `AuthContextInterface $context` and `UserContext $userContext` to the controller.

![image](https://github.com/user-attachments/assets/f3640cc3-27f4-4313-82ee-41a6bc7a8eba)

The problem did not reproduce. Could you provide a reproducible example in the form of a GitHub repository?

**Comment by roxblnfk** [comment] 2024-11-25 20:22
Should be fixed with `3.14.7`

**Comment by roxblnfk** [comment] 2024-12-11 19:15
Feel free to reopen if the bug still exists

**Closed** 2024-12-11 19:15 UTC
Labels: Bug

**Comment by vokomarov** [comment] 2025-01-05 12:07
For me it is fixed now. Thanks.

It was still an issue even after upgrade to `3.14.8` because I was extending `FakeHttp` to implement `optionsJson` method, as my test cases uses OPTIONS requests. Now after upgrade I am not able to extend `FakeHttp` anymore because of private method `TestCase::runScopes`, so I am not able to instantiate my own extended `FakeHttp`.

**Comment by roxblnfk** [comment] 2025-01-05 18:16
Looks like a new issue for the testing package 🤔
